### ISSUE TITLE
Implement ALL the staff

### ISSUE THREAD

**Issue by sugar700** [HoeenCoder/Pokemon-Showdown#10]
Here is list of staff for convenience purposes

Administrators (~):

- [ ] Antar
- [ ] antemortem
- [ ] chaos
- [x] EV
- [ ] The Immortal
- [ ] Zarel

Leaders (&):

- [ ] asgdf
- [ ] atomicllamas
- [ ] Birkal
- [ ] bumbadadabum
- [ ] Bummer
- [ ] cant say
- [ ] CELTIC
- [ ] DougJustDoug
- [ ] dtc
- [ ] Hikari
- [ ] Hootie
- [ ] IronBullet
- [ ] Jellicent
- [ ] Jirachee
- [x] kamikaze
- [ ] Mekkah
- [ ] Nexus
- [ ] Oglemi
- [ ] Orda-Y
- [ ] plumberjack
- [ ] Quite Quiet
- [ ] raseri
- [ ] Raven
- [ ] Sam
- [x] Scotteh
- [ ] sirDonovan
- [ ] TDK
- [ ] tennisace
- [ ] verbatim

Moderators (@):

- [ ] Ace
- [ ] Acedia
- [ ] aeo
- [x] AndrewGoncel >_>
- [ ] Asty
- [ ] Austin
- [x] Beowulf
- [ ] Berserking Now
- [ ] biggie
- [ ] Cerberax
- [ ] coolstorybrobat
- [ ] Coronis
- [ ] Duck
- [ ] Eos
- [ ] Eyan
- [ ] Feliburn
- [ ] Formerhope
- [ ] galbia
- [ ] Giagantic
- [ ] grimAuxiliatrix
- [ ] halite
- [ ] Haund
- [ ] Hippopotas
- [x] HoeenHero
- [ ] HYDRO IMPACT
- [x] innovamania
- [ ] Jac
- [ ] jas61292
- [ ] jdarden
- [ ] kupo
- [ ] LegitimateUsername
- [x] Level 51
- [ ] Marshmallon
- [ ] mORFEnT (◔̯◔)
- [ ] Osiris
- [ ] Paradise~
- [ ] phil
- [ ] pookie
- [ ] prem
- [ ] qtrx
- [ ] Quote
- [ ] Reverb
- [ ] Rico
- [ ] ridaz
- [ ] Scyther NO Swiping
- [ ] shrang
- [ ] Sigilyph
- [ ] Skitty
- [ ] SpaceBass
- [ ] Subject 18
- [ ] Temporaryanonymous
- [x] Teremiare
- [ ] Theorymon
- [ ] Tiksi
- [ ] Timbuktu
- [x] Trickster
- [ ] urkerab
- [ ] WaterBomb
- [ ] Winry
- [x] xfix

Drivers (%):

- [ ] 2xTheTap
- [ ] Acast
- [x] Aelita
- [ ] Akir
- [ ] Amingo
- [ ] ant
- [ ] Arcticblast
- [ ] Arti & Cuno ♥
- [ ] Ascriptmaster
- [x] Ast☆arA
- [ ] AuzBat
- [ ] barton
- [ ] Bondie
- [ ] brandon
- [ ] Cheese
- [ ] Chloe
- [ ] ciran
- [ ] Crestfall
- [ ] Darnell
- [ ] Disjunction'!!
- [ ] DragonWhale ☼
- [ ] E4 Flint
- [ ] GeoffBruedly
- [ ] GoodMorningEspeon
- [ ] HeaLnDeaL
- [ ] H N G M N
- [ ] Hugendugen
- [x] Imas♆
- [ ] Iyarito ☾
- [ ] joethemaster
- [x] Joim
- [x] Kalalokki
- [ ] kay
- [ ] LifeisDANK
- [ ] Lyren
- [ ] makiri
- [ ] Marty
- [ ] Megazard
- [x] MochaMint
- [ ] Mr.Aldo
- [ ] nv
- [ ] Okuu
- [x] panpawn
- [ ] qsxs^♥^qsxs
- [ ] ryan
- [ ] Slayer95
- [ ] Soccer
- [ ] SteelEdges
- [ ] Struchni
- [ ] Sweep
- [ ] Swirlyder
- [ ] Team❄️Pokepals
- [ ] Toast++
- [ ] v4
- [ ] Vacate
- [ ] xJoelituh
- [ ] yuki
- [x] Zod

**Comment by HoeenCoder** [comment]
The other issue is a more detailed list of what exactly is done per set.

**Use this issue to claim sets to code please!**

**Comment by AndrewGoncel** [comment]
claiming joim

**Comment by CheeseMuffin** [comment]
gonna work on tempanonymous

**Comment by DeathlyPlays** [comment]
I'll take HealNDeal, Quote, Morfent, Vacate (if I can reach him)

**Comment by DeathlyPlays** [comment]
Claiming Quote, HealNDeal, Lyren, Slayer95, and DougJustDoug

**Comment by DeathlyPlays** [comment]
Oh and Morfent
