### ISSUE TITLE
Bug Reports

### ISSUE THREAD

**Issue by AndrewGoncel** [HoeenCoder/Pokemon-Showdown#34]
Comment here the bugs you find.

Trickster's innate not setting gravity
Trickster's custom move not setting Trick Room
"Zod's custom move used teremiare's custom move to steal stats and pass them, however the stats weren't passed on to the mon I sent out."

**Comment by CheeseMuffin** [comment]
panpawn's move should do 150 damage, not 150 base power.

**Comment by Spandamn** [comment]
#35 Should fix the above and Trickster

**Comment by CheeseMuffin** [comment]
[20:33:45] %DragonWhale: can i change dragon claw on garchomp to dragon rush? My github is being dumb so I can't figure out how to pr myself
